### ISSUE TITLE
GCID: Site throws an error when you search for a dataset by name

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#128]
From Shaun:

```
Traceback (most recent call last):
"/var/log/apache2/error.log.1" [readonly] 107L, 8486C                                                 1,1           Top
    self._handle_result(self._connection.cmd_query(stmt))
  File "/opt/Python-3.7.3/lib/python3.7/site-packages/mysql/connector/connection.py", line 598, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/opt/Python-3.7.3/lib/python3.7/site-packages/mysql/connector/connection.py", line 486, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.DatabaseError: 1191 (HY000): Can't find FULLTEXT index matching the column list
```

**Comment by jorvis** [comment]
Table was missing the latest multi-column index:

```
mysql> alter table dataset add FULLTEXT KEY `text_with_geo_pubmed_idx` (`title`,`ldesc`,`geo_id`,`pubmed_id`);
Query OK, 0 rows affected (0.20 sec)
Records: 0  Duplicates: 0  Warnings: 0
```
