### ISSUE TITLE
Saving genecart fails (via multigene curator tool)

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#62]
Think there may be a bug in save_new_genecart.cgi:
```
[Wed Oct 13 20:26:50.863485 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215: Traceback (most recent call last):: /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
[Wed Oct 13 20:26:50.863547 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215:   File "/var/www/cgi/save_new_genecart.cgi", line 30, in <module>: /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
[Wed Oct 13 20:26:50.863556 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215:     main(): /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
[Wed Oct 13 20:26:50.863584 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215:   File "/var/www/cgi/save_new_genecart.cgi", line 22, in main: /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
[Wed Oct 13 20:26:50.863599 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215:     form = cgi.FieldStorage(): /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
[Wed Oct 13 20:26:50.863639 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215:   File "/opt/Python-3.7.3/lib/python3.7/cgi.py", line 491, in __init__: /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
[Wed Oct 13 20:26:50.863652 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215:     self.read_single(): /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
[Wed Oct 13 20:26:50.863684 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215:   File "/opt/Python-3.7.3/lib/python3.7/cgi.py", line 682, in read_single: /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
[Wed Oct 13 20:26:50.863696 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215:     self.read_binary(): /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
[Wed Oct 13 20:26:50.863729 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215:   File "/opt/Python-3.7.3/lib/python3.7/cgi.py", line 704, in read_binary: /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
[Wed Oct 13 20:26:50.863742 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215:     self.file.write(data): /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
[Wed Oct 13 20:26:50.863766 2021] [cgi:error] [pid 23] [client 172.18.0.1:57286] AH01215: TypeError: write() argument must be str, not bytes: /var/www/cgi/save_new_genecart.cgi, referer: http://localhost:8080/multigene_curator.html
```

Seems whatever is being passed to the self.file.write() is bytes instead of string.

My payload:
```
{"session_id":"ee95e48d-c512-4083-bf05-ca9f65e2c12a","label":"sadkins_test","genes":[{"id":"ENSMUSG00000028441","gene_symbol":"1110017D15Rik"},{"id":"ENSMUSG00000049154","gene_symbol":"Fam183b"},{"id":"ENSMUSG00000062252","gene_symbol":"Lhfpl5"},{"id":"ENSMUSG00000038132","gene_symbol":"Rbm24"},{"id":"ENSMUSG00000041476","gene_symbol":"Smpx"}]}
```

**Comment by jorvis** [comment]
OK, several recent commits and gene cart saving via JSON submission is fixed.  Example usage:

https://github.com/IGS/gEAR/blob/main/www/js/compare_datasets.js#L546

**Comment by adkinsrs** [comment]
committed multigene curator GeneCart call/save.  Also fixed a genecart loading bug at the same time
