### ISSUE TITLE
All displays currently failing on my local with "ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers'"

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#70]
I've made sure my code was current and restarted apache with the same result.  Can replicate with all datasets I try to view.  Apache log shows:

```
[Wed Oct 20 10:53:40.327252 2021] [wsgi:error] [pid 16199] [remote 192.168.1.16:48810] mod_wsgi (pid=16199): Failed to exec Python script file '/var/www/html/api/api.wsgi'.
[Wed Oct 20 10:53:40.327330 2021] [wsgi:error] [pid 16199] [remote 192.168.1.16:48810] mod_wsgi (pid=16199): Exception occurred processing WSGI script '/var/www/html/api/api.wsgi'.
[Wed Oct 20 10:53:40.327815 2021] [wsgi:error] [pid 16199] [remote 192.168.1.16:48810] Traceback (most recent call last):
[Wed Oct 20 10:53:40.327849 2021] [wsgi:error] [pid 16199] [remote 192.168.1.16:48810]   File "/var/www/html/api/api.wsgi", line 8, in <module>
[Wed Oct 20 10:53:40.327857 2021] [wsgi:error] [pid 16199] [remote 192.168.1.16:48810]     from api import app as application
[Wed Oct 20 10:53:40.327866 2021] [wsgi:error] [pid 16199] [remote 192.168.1.16:48810]   File "/home/jorvis/Dropbox/git/gEAR/www/api/api.py", line 16, in <module>
[Wed Oct 20 10:53:40.327872 2021] [wsgi:error] [pid 16199] [remote 192.168.1.16:48810]     from flask_restful import Resource, Api
[Wed Oct 20 10:53:40.327880 2021] [wsgi:error] [pid 16199] [remote 192.168.1.16:48810]   File "/opt/Python-3.7.3/lib/python3.7/site-packages/flask_restful/__init__.py", line 14, in <module>
[Wed Oct 20 10:53:40.327886 2021] [wsgi:error] [pid 16199] [remote 192.168.1.16:48810]     from flask.helpers import _endpoint_from_view_func
[Wed Oct 20 10:53:40.327911 2021] [wsgi:error] [pid 16199] [remote 192.168.1.16:48810] ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers' (/opt/Python-3.7.3/lib/python3.7/site-packages/flask/helpers.py)
```

**Comment by adkinsrs** [comment]
https://github.com/flask-restful/flask-restful/pull/913

Referenced in https://stackoverflow.com/questions/67496857/cannot-import-name-endpoint-from-view-func-from-flask-helpers-in-python

**Comment by jorvis** [comment]
OK, found the problem:

```
$ /opt/Python-3.7.3/bin/python3
Python 3.7.3 (default, May  1 2019, 10:45:02) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flask
>>> print(flask.__version__)
2.0.1
>>> 
```

As I suspected, my install of another tool updated that Python directory.
