### ISSUE TITLE
errors for individual datasets in particular views

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#858]
hi guys - i didnt want to start tons of tickets for these, so im putting them together here - let me know if youd like me to do this differently:

1]
in link: "https://nemoanalytics.org/projection.html?projection_algorithm=pca&multipattern_plots=0&projection_source=CellCycleGenes.Seurat&layout_id=NeocortexDevoHsInVitro"

dataset: "Structurally Conserved Primate LncRNAs Are Transiently Expressed during Human Cortical Differentiation and Influence Cell-Type-Specific Genes - Human CO Timecourse (Field et al., Stem Cell Rep 2019)"

give this error: "Error: No common genes between the target dataset (63687 genes) and the pattern file (97 genes)." but i am quite sure the genes should overlap

2]
in link: "https://nemoanalytics.org/projection.html?projection_algorithm=nmf&multipattern_plots=0&projection_source=MammCtxDev.jNMF.p40&layout_id=NeocortexEvoDevo"

dataset: "Spatiotemporal transcriptomic divergence across human and macaque brain development - Bulk Macaque (Zhu et al., Science 2018)"

give this error: "Error: Something went wrong with the projection-creating step."

and dataset: "Establishing Cerebral Organoids as Models of Human-Specific Brain Evolution - Human Primary v. Macaque Primary (Pollen et al., Cell 2019)"

gives this error: "Error: No common genes between the target dataset (49360 genes) and the pattern file (15469 genes)." but i am quite sure the genes should overlap. i think we may have had an issue with this dataset before.

3]
in link: "https://nemoanalytics.org/projection.html?projection_algorithm=nmf&multipattern_plots=0&projection_source=MammCtxDev.jNMF.p7&layout_id=NeocortexEvoDevo"

i get same 2 errors as in #2 above

4]
in link: "https://nemoanalytics.org/projection.html?projection_algorithm=nmf&multipattern_plots=0&projection_source=MammCtxDev.jNMF.p40&layout_id=NeocortexDevoHsInVitro"

i get the same error as in #1 above

**Comment by adkinsrs** [comment]
I took a look at the "Structurally Conserved Primate LncRNAs Are Transiently Expressed during Human Cortical Differentiation and Influence Cell-Type-Specific Genes - Human CO Timecourse (Field et al., Stem Cell Rep 2019)" dataset and it looks like the h5ad file does not contain Ensembl IDs for the AnnData var object.

```
                            gene_symbol
gene
CATG00000000004.1      NOsymbolMapped.1
CATG00000000008.1      NOsymbolMapped.2
CATG00000000010.1      NOsymbolMapped.3
CATG00000000011.1      NOsymbolMapped.4
CATG00000000015.1      NOsymbolMapped.5
...                                 ...
XLOC_069559        NOsymbolMapped.31394
XLOC_069560        NOsymbolMapped.31395
XLOC_069561        NOsymbolMapped.31396
XLOC_069581        NOsymbolMapped.31397
XLOC_069614        NOsymbolMapped.31398

[63687 rows x 1 columns]
```

I checked the "Establishing cerebral..." dataset and there are a mix of Ensembl IDs and "NaN" values in the adata.var.index.  About 20K of the 49K are valid Ensembl IDs. I do not know how these were derived but I guess there was a process to map the gene symbol name (human) to a derived Ensembl ID, and many of them id not map.

Still need to investigate the "Spatiotemporal transcriptomic divergence ..." dataset

**Comment by adkinsrs** [comment]
## Spatiotemporal transcriptomic divergence ... dataset

Checked the cloud run function and got this error stack

```python
Traceback (most recent call last):
  File "/app/rfuncs.py", line 72, in run_projectR_cmd
    projection_patterns_r_matrix = projectR.projectR(data=target_r_matrix, loadings=loading_r_matrix, full=False)
  File "/usr/local/lib/python3.10/site-packages/rpy2/robjects/functions.py", line 201, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "/usr/local/lib/python3.10/site-packages/rpy2/robjects/functions.py", line 124, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.10/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rpy2/rinterface.py", line 810, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in p2P[match(rownames(p2P), rownames(As4P)), ] : "

Incorrect number of dimensions
```

Seems like there is a mismatch in dimensions between the dataset gene indexes and the pattern gene index. I'm guessing one of these must be cast into a list of lists or something.  Since this isn't a "every dataset or every pattern issue", there must be something about this combination. For what it's worth there are 13.5K common genes between dataset and pattern file, so the genes are mapping fine, at least in the API call.

**Comment by carlocolantuoni** [comment]
for the "Structurally Conserved... dataset" - i think you are correct about the problem being related to the version number appended to the ENSG ids - when i see this i remove them before upload, but i did not upload this dataset. is it possible to run a script to snip off the ".X" from each id?

for the "Establishing cerebral... dataset" - this is a human/macaque dataset so should have had ENSGxxxx or ENSMMUGxxxx IDs - can yo look at the ENSM ids you describe to see if the are are more letters after ENSM? - for example mouse is ENSMUSGxxxx

ill look at the last incorrect dims error now
