### ISSUE TITLE
Layout member retrieval -  'NoneType' object has no attribute 'get_singlegene_members'

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#896]
While having the students curate a display I was watching the error logs and saw many instances of this appearing in Apache's error log.

Ronna was out of my range of hearing when she guided them so I couldn't hear which dataset was being curated, so that may be necessary to repeat the issue, but I wanted to log it here.

Log filled with:

```
Traceback (most recent call last):
  File "/var/www/cgi/search_genes.cgi", line 111, in <module>
    main()
  File "/var/www/cgi/search_genes.cgi", line 84, in main
    label="\"{0}\" in {1}".format(gene_symbol_label, layout.label),
AttributeError: 'NoneType' object has no attribute 'label'
Traceback (most recent call last):
  File "/var/www/cgi/get_users_layout_members.cgi", line 60, in <module>
    main()
  File "/var/www/cgi/get_users_layout_members.cgi", line 33, in main
    layout.get_singlegene_members()
AttributeError: 'NoneType' object has no attribute 'get_singlegene_members'
Traceback (most recent call last):
  File "/var/www/cgi/search_genes.cgi", line 111, in <module>
    main()
  File "/var/www/cgi/search_genes.cgi", line 84, in main
    label="\"{0}\" in {1}".format(gene_symbol_label, layout.label),
AttributeError: 'NoneType' object has no attribute 'label'
Traceback (most recent call last):
  File "/var/www/cgi/get_users_layout_members.cgi", line 60, in <module>
    main()
  File "/var/www/cgi/get_users_layout_members.cgi", line 33, in main
    layout.get_singlegene_members()
AttributeError: 'NoneType' object has no attribute 'get_singlegene_members'
Traceback (most recent call last):
  File "/var/www/cgi/search_genes.cgi", line 111, in <module>
    main()
  File "/var/www/cgi/search_genes.cgi", line 84, in main
    label="\"{0}\" in {1}".format(gene_symbol_label, layout.label),
AttributeError: 'NoneType' object has no attribute 'label'
Traceback (most recent call last):
  File "/var/www/cgi/get_users_layout_members.cgi", line 60, in <module>
    main()
  File "/var/www/cgi/get_users_layout_members.cgi", line 33, in main
    layout.get_singlegene_members()
AttributeError: 'NoneType' object has no attribute 'get_singlegene_members'
Traceback (most recent call last):
  File "/var/www/cgi/search_genes.cgi", line 111, in <module>
    main()
  File "/var/www/cgi/search_genes.cgi", line 84, in main
    label="\"{0}\" in {1}".format(gene_symbol_label, layout.label),
AttributeError: 'NoneType' object has no attribute 'label'
Traceback (most recent call last):
  File "/var/www/cgi/get_users_layout_members.cgi", line 60, in <module>
    main()
  File "/var/www/cgi/get_users_layout_members.cgi", line 33, in main
    layout.get_singlegene_members()
AttributeError: 'NoneType' object has no attribute 'get_singlegene_members'
```

**Comment by adkinsrs** [comment]
Neither search_genes.cgi nor get_users_layout_members.cgi are called within the multigene curator though

**Comment by jorvis** [comment]
Maybe it was a total coincidence that it happened at the same time.  Not able to duplicate it with front page searches atm.

**Comment by adkinsrs** [comment]
Made branch "bugfix-get-users-layout-members" to address this

**Comment by adkinsrs** [comment]
Merged branch for now.  Leaving ticket open as we have yet to ascertain the UI situation triggering these (JS-related).  My hunch is the "selected_dc_share_id" variable from dataset_collection_selector.js is being accessed while still being null.

**Comment by adkinsrs** [comment]
I'm closing for now, and if this persists, can reopen
