### ISSUE TITLE
Error log: Layouts missing labels?

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#940]
Seeing a lot of this in the apache error log:

```
Traceback (most recent call last):
  File "/var/www/cgi/search_genes.cgi", line 111, in <module>
    main()
  File "/var/www/cgi/search_genes.cgi", line 84, in main
    label="\"{0}\" in {1}".format(gene_symbol_label, layout.label),
AttributeError: 'NoneType' object has no attribute 'label'
```

**Comment by jorvis** [comment]
I started by adding some apache logging to search_genes.cgi so I can see session and layouts being searched.

**Comment by adkinsrs** [comment]
I think one of the common elements to both this and #896 is that both CGI scripts are called in the Javascript stack using the "selected_dc_share_id" defined in the dataset_collection selector. So there may be an edge case where this value is not being assigned neither the default layout share ID nor the selected collection share ID.

**Comment by jorvis** [comment]
Agreed.  I'm going to at least fix things where where the user history log isn't created if there isn't a selected layout.

**Comment by jorvis** [comment]
I pushed the hotfix branch commit
